global:
  resolve_timeout: 5m
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@finn.local'

route:
  group_by: ['alertname', 'job']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'

  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      repeat_interval: 30m

receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://webhook:5000/'
        send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://webhook:5000/critical'
        send_resolved: true
    email_configs:
      - to: 'admin@finn.local'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']